#!/bin/sh
#
# Writes keystore.properties so local release builds are signed with the same key
# as the CI ones, making them installable over each other. The password is read
# without echo and never printed nor stored anywhere else.
#
# Usage: ./scripts/setup_keystore_properties.sh [keystore-file]

set -e

KEYSTORE="${1:-release.jks}"
OUTPUT="keystore.properties"

if [ ! -f "$KEYSTORE" ]; then
    echo "ERROR: keystore not found: $KEYSTORE" >&2
    echo "Pass its path as the first argument, e.g. ./scripts/setup_keystore_properties.sh ~/keys/release.jks" >&2
    exit 1
fi

if [ -f "$OUTPUT" ]; then
    printf '%s already exists. Overwrite? [y/N] ' "$OUTPUT"
    read -r answer
    case "$answer" in
        [yY]*) ;;
        *) echo "Aborted."; exit 0;;
    esac
fi

printf 'Keystore password: '
stty -echo 2>/dev/null || true
read -r PASSWORD
stty echo 2>/dev/null || true
printf '\n'

if [ -z "$PASSWORD" ]; then
    echo "ERROR: empty password." >&2
    exit 1
fi

LISTING=$(keytool -list -keystore "$KEYSTORE" -storepass "$PASSWORD" 2>&1) || {
    echo "ERROR: that password does not open $KEYSTORE." >&2
    echo "       (keytool said: $(echo "$LISTING" | head -1))" >&2
    exit 1
}

# The alias is the first field of the entry line, before the comma.
ALIAS=$(echo "$LISTING" | sed -n 's/^\([^,]*\),.*PrivateKeyEntry.*$/\1/p' | head -1)
if [ -z "$ALIAS" ]; then
    ALIAS=$(echo "$LISTING" | sed -n 's/^\([^,]*\),.*$/\1/p' | grep -v '^$' | tail -1)
fi
if [ -z "$ALIAS" ]; then
    echo "ERROR: could not determine the key alias from the keystore listing." >&2
    exit 1
fi

umask 077
cat > "$OUTPUT" <<PROPS
# Generated by scripts/setup_keystore_properties.sh -- git-ignored, keep it local.
# PKCS12 keystores use one password for both the store and the key.
storeFile=$KEYSTORE
storePassword=$PASSWORD
keyAlias=$ALIAS
keyPassword=$PASSWORD
PROPS

echo "Wrote $OUTPUT (alias: $ALIAS, permissions: $(ls -l "$OUTPUT" | cut -c1-10))"
echo "Local release builds are now signed with the release key; ./install.sh no longer"
echo "conflicts with the APKs published by the CI."
